name: Security Audit

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  supply-chain:
    name: 'cargo-audit'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # 1.91.1
        with:
            toolchain: 1.91.1

      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          cache-on-failure: true

      - name: Install cargo-audit
        run: cargo install cargo-audit@0.22.0 --force --locked

      - name: Check for audit warnings
        run: cargo audit -D warnings
        continue-on-error: true

      - name: Check for vulnerabilities
        run: cargo audit
